# Simple workflow for deploying static content to GitHub Pages
name: GitHub Pages

on:
  # Runs on pushes, if all conditions are met:
  push:
    # ... on the master branch ...
    branches:
      - 'master'
    # ... skip tags only ...
    tags-ignore:
      - '**'
    # ... any of these files changes ...
    paths:
      - 'website/typedoc.json'
      - 'website/package.json'
      - 'website/assets/css/*.css'
      - '**/tsconfig*.json'
      - 'src/**/*.ts'
      - 'README.md'
      - '.github/workflows/publish-github-pages.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4.1.1

      - name: Use Nodejs
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install
          npm install -C website

      - name: Compile TypeScript
        run: npm run compile

      - name: Generate TypeDocs
        run: npm run typedoc -C website

      - name: Setup Pages
        # https://github.com/actions/configure-pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Upload entire website
          path: './website/html'

      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4.0.4
